# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/htnn.mosn.io_httpfilterpolicies.yaml
- bases/htnn.mosn.io_consumers.yaml
- bases/htnn.mosn.io_serviceregistries.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:

configurations:
- kustomizeconfig.yaml
