coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5% # 75%~80% is the yellow zone - ok to merge but should increase it
        if_ci_failed: error
    patch:
      default:
        target: 70% # lower target for single change
        if_ci_failed: error
ignore:
  # test files
  - "api/plugins/tests"
  - "plugins/tests/"
  - "controller/tests"
  - "e2e/"
  - "**/mock.go"
  # examples
  - "examples/"
  # tools
  - "./site/"
  - "./tools/"
  # generated code
  - "**/*.pb.go"
  - "**/*.pb.validate.go"
  - '**/zz_generated.deepcopy.go'
  - "types/pkg/client"
