run:
  deadline: 5m

linters:
  enable:
    # sorted in alphabetic order
    - bodyclose
    - contextcheck
    - errcheck
    - exportloopref
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - nilerr
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gocritic:
    disabled-tags:
      - style
      - experimental
      - opinionated
  unparam:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go # unit tests
      linters:
        - errcheck
        - gosec
        - unparam
    - path: tests/ # integration tests
      linters:
        - bodyclose
        - errcheck
        - gosec
        - unparam
    - path: e2e/ # e2e tests
      linters:
        - bodyclose
        - errcheck
        - gosec
        - unparam
  # Show the complete output
  max-issues-per-linter: 0
  max-same-issues: 0
