run:
  deadline: 5m

linters:
  enable:
    # sorted in alphabetic order
    - bodyclose
    - contextcheck
    - errcheck
    - exportloopref
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gocritic:
    disabled-tags:
      - style
      - experimental
      - opinionated
  gosec:
    excludes:
      - G402 # TLS InsecureSkipVerify may be true.
  revive:
    rules:
      - name: receiver-naming
      - name: var-naming
  unparam:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go # unit tests
      linters:
        - errcheck
        - forcetypeassert
        - gosec
        - unparam
    - path: tests/ # integration tests
      linters:
        - bodyclose
        - errcheck
        - forcetypeassert
        - gosec
        - unparam
    - path: plugins/ # too much plugin config type assert in the plugins
      linters:
        - forcetypeassert
    - path: registries/ # ditto
      linters:
        - forcetypeassert
    - path: dynamicconfigs/ # ditto
      linters:
        - forcetypeassert
  # Show the complete output
  max-issues-per-linter: 0
  max-same-issues: 0
