run:
  deadline: 10m

linters:
  enable:
    # sorted in alphabetic order
    - bodyclose
    - contextcheck
    - errcheck
    - exportloopref
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - nilerr
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  unparam:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: tests/
      linters:
        - bodyclose
        - errcheck
        - gosec
        - unparam
  # Show the complete output
  max-issues-per-linter: 0
  max-same-issues: 0
