run:
  timeout: 5m

linters:
  enable:
    # sorted in alphabetic order
    - bodyclose
    - contextcheck
    - dupl
    - dupword
    - errcheck
    - copyloopvar
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - nilerr
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  dupl:
    threshold: 100  # minimum number of tokens to trigger duplication warning
  dupword:
    # ignore some common patterns
    ignore:
      - "google"
      - "apache"
      - "github"
  gocritic:
    disabled-tags:
      - style
      - experimental
      - opinionated
  gosec:
    excludes:
      - G115 # Ignore "integer overflow conversion int". Since we call the conversion explicitly, we know what we do.
      - G402 # TLS InsecureSkipVerify may be true.
  revive:
    rules:
      - name: receiver-naming
      - name: var-naming
  unparam:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go # unit tests
      linters:
        - errcheck
        - forcetypeassert
        - gosec
        - unparam
    - path: tests/ # integration tests
      linters:
        - bodyclose
        - errcheck
        - forcetypeassert
        - gosec
        - unparam
    - path: plugins/ # too much plugin config type assert in the plugins
      linters:
        - forcetypeassert
    - path: registries/ # ditto
      linters:
        - forcetypeassert
    - path: dynamicconfigs/ # ditto
      linters:
        - forcetypeassert
    - path: \.pb\.go$ # generated protobuf files
      linters:
        - dupl
        - dupword
    - path: \.pb\.validate\.go$ # generated validation files
      linters:
        - dupl
        - dupword
  # Show the complete output
  max-issues-per-linter: 0
  max-same-issues: 0
