run:
  deadline: 5m

linters:
  enable:
    # sorted in alphabetic order
    - bodyclose
    - contextcheck
    - cyclop
    - errcheck
    - exportloopref
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - nilerr
    - staticcheck
    - unconvert
    - unparam
    - unused

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 20
    package-average: 10
    skip-tests: true
  gocritic:
    disabled-tags:
      - style
      - experimental
      - opinionated
  unparam:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
    - path: tests/
      linters:
        - bodyclose
        - errcheck
        - gosec
        - unparam
  # Show the complete output
  max-issues-per-linter: 0
  max-same-issues: 0
