header:
  license:
    spdx-id: Apache-2.0
    content: |
      Copyright The HTNN Authors.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.

  paths-ignore:
    # ignore doc, testdata and configuration
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'CODEOWNERS'
    - '**/testdata/**'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.toml'
    # ignore file controlled by tools
    - '**/go.sum'
    - 'buf.lock'
    - 'Chart.lock'
    # files can't add license
    - '**/*.pb.validate.go'
    - '**/*.json'
    - '**/*.txt'
    - '**/*.patch'
    - '**/*.gotmpl'
    - '**/*.tpl'
    - '.ignore_words'
    # files from other projects
    - 'site/assets/**'
    - 'site/layouts/**'
    - 'api/internal/cookie/cookie.go'
    - 'controller/registries/nacos/config.go'
    - 'external/**'
  comment: on-failure

dependency:
  files:
    - go.mod
  excludes:
    - name: github.com/dgryski/trifles # the author adds MIT License later
    - name: github.com/rcrowley/go-metrics # this repo uses BSD-2-Clause-Views, which is not recognized in skywalking-eye 0.6
    - name: github.com/kr/logfmt # the author adds MIT License later
    - name: github.com/pascaldekloe/goe # use CC0-1.0 License
    - name: github.com/zeebo/assert # use CC0-1.0 License
    - name: github.com/ajstarks/deck # use CC-BY-4.0 License
    - name: github.com/ajstarks/deck/generate # use CC-BY-4.0 License
    - name: github.com/ajstarks/svgo # use CC-BY-4.0 License
    - name: github.com/golang/freetype # dual license: we choose the FreeType License, which is similar to the original BSD license with an advertising clause
    - name: github.com/chzyer/logex # use MIT License
    - name: github.com/JohnCGriffin/overflow # use MIT License added in the README
    - name: github.com/hudl/fargo # use BSD-2-Clause license, which is not recognized in sentinel-golang 1.0.4
    - name: github.com/lightstep/lightstep-tracer-common/golang/gogo # use MIT license, which is not recognized in sentinel-golang 1.0.4
    - name: github.com/streadway/handy # use BSD-2-Clause license, which is not recognized in sentinel-golang 1.0.4
