// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc1
// source: types/plugins/basicauth/config.proto

package basicauth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义 Basic Auth 插件的配置
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名和密码对
	Credentials   map[string]string `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_types_plugins_basicauth_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_types_plugins_basicauth_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_types_plugins_basicauth_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

var File_types_plugins_basicauth_config_proto protoreflect.FileDescriptor

const file_types_plugins_basicauth_config_proto_rawDesc = "" +
	"\n" +
	"$types/plugins/basicauth/config.proto\x12\x17types.plugins.basicauth\"\x9c\x01\n" +
	"\x06Config\x12R\n" +
	"\vcredentials\x18\x01 \x03(\v20.types.plugins.basicauth.Config.CredentialsEntryR\vcredentials\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B&Z$mosn.io/htnn/types/plugins/basicauthb\x06proto3"

var (
	file_types_plugins_basicauth_config_proto_rawDescOnce sync.Once
	file_types_plugins_basicauth_config_proto_rawDescData []byte
)

func file_types_plugins_basicauth_config_proto_rawDescGZIP() []byte {
	file_types_plugins_basicauth_config_proto_rawDescOnce.Do(func() {
		file_types_plugins_basicauth_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_plugins_basicauth_config_proto_rawDesc), len(file_types_plugins_basicauth_config_proto_rawDesc)))
	})
	return file_types_plugins_basicauth_config_proto_rawDescData
}

var file_types_plugins_basicauth_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_plugins_basicauth_config_proto_goTypes = []any{
	(*Config)(nil), // 0: types.plugins.basicauth.Config
	nil,            // 1: types.plugins.basicauth.Config.CredentialsEntry
}
var file_types_plugins_basicauth_config_proto_depIdxs = []int32{
	1, // 0: types.plugins.basicauth.Config.credentials:type_name -> types.plugins.basicauth.Config.CredentialsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_types_plugins_basicauth_config_proto_init() }
func file_types_plugins_basicauth_config_proto_init() {
	if File_types_plugins_basicauth_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_plugins_basicauth_config_proto_rawDesc), len(file_types_plugins_basicauth_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_plugins_basicauth_config_proto_goTypes,
		DependencyIndexes: file_types_plugins_basicauth_config_proto_depIdxs,
		MessageInfos:      file_types_plugins_basicauth_config_proto_msgTypes,
	}.Build()
	File_types_plugins_basicauth_config_proto = out.File
	file_types_plugins_basicauth_config_proto_goTypes = nil
	file_types_plugins_basicauth_config_proto_depIdxs = nil
}
