IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreURLs:
  - https://mosn.io/ # fake base url for now
  - http://localhost:1313/ # path used in local dev
  # ignore code generated links from the GitHub component
  - https://github.com/mosn/htnn/edit/
  - https://github.com/mosn/htnn/new
  - https://github.com/mosn/htnn/issues/new
IgnoreDirs:
  # the links in print section is known broken. See https://github.com/google/docsy/issues/1348
  - "/_print/"
