name: "Feature request"
description: Suggest an idea to improve HTNN
body:
  - type: textarea
    id: idea
    attributes:
      label: Description
      description: Describe the new feature you want to support clearly.
    validations:
      required: false
  - type: textarea
    id: scenes
    attributes:
      label: Use Scenes
      description: Describe your use scenes (why need this feature).
    validations:
      required: true
  - type: textarea
    id: advice
    attributes:
      label: Advice
      description: Describe the advice or solution of this new feature.
    validations:
      required: false
