name: "Ask Question"
description: Ask a question about usage or features
body:
  - type: textarea
    id: question
    attributes:
      label: Description
      description: Describe the question.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Show the environment related to the question.
      value: |
        - HTNN version:
    validations:
      required: true
