name: "Bug Report"
description: Create a report to help us improve
body:
  - type: textarea
    id: describe
    attributes:
      label: Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what happened instead.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: minimal-case
    attributes:
      label: Reproducible Code
      description: Minimal yet complete reproducible code (or GitHub URL to code)
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Show the environment related to the report.
      value: |
        - HTNN version:
    validations:
      required: true
