# This file lists all HTNN controller's configuration and their default value.


# If this is set to true, support for Kubernetes gateway-api will be enabled.
# In addition to this being enabled, the gateway-api CRDs need to be installed.
enable_gateway_api: true
# Enable embedded mode so that HTNN won't check the annotation of the target resource.
enable_embedded_mode: true
# Enable Native plugin. Sometimes we may need to disable all native plugins, because:
# 1. Only want to use Go plugins
# 2. A custom Envoy is used and it doesn't support all Envoy's http filters as the default
# open source one.
enable_native_plugin: true
envoy:
  # Should match the Go shared library put in the data plane image
  go_so_path: /etc/libgolang.so
istio:
  # Should match istio's rootNamespace configuration.
  # See https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig for more info.
  root_namespace: "istio-system"
