# permissions for end users to view consumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: consumer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: consumer-viewer-role
rules:
- apiGroups:
  - htnn.mosn.io
  resources:
  - consumers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - htnn.mosn.io
  resources:
  - consumers/status
  verbs:
  - get
