---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mosn.io
  resources:
  - httpfilterpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mosn.io
  resources:
  - httpfilterpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - mosn.io
  resources:
  - httpfilterpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservice
  verbs:
  - get
  - list
  - watch
