// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: tests/integration/plugins/config.proto

package plugins

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Need    bool `protobuf:"varint,1,opt,name=need,proto3" json:"need,omitempty"`
	Decode  bool `protobuf:"varint,2,opt,name=decode,proto3" json:"decode,omitempty"`
	Encode  bool `protobuf:"varint,3,opt,name=encode,proto3" json:"encode,omitempty"`
	Headers bool `protobuf:"varint,4,opt,name=headers,proto3" json:"headers,omitempty"`
	Data    bool `protobuf:"varint,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_integration_plugins_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integration_plugins_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_tests_integration_plugins_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetNeed() bool {
	if x != nil {
		return x.Need
	}
	return false
}

func (x *Config) GetDecode() bool {
	if x != nil {
		return x.Decode
	}
	return false
}

func (x *Config) GetEncode() bool {
	if x != nil {
		return x.Encode
	}
	return false
}

func (x *Config) GetHeaders() bool {
	if x != nil {
		return x.Headers
	}
	return false
}

func (x *Config) GetData() bool {
	if x != nil {
		return x.Data
	}
	return false
}

var File_tests_integration_plugins_config_proto protoreflect.FileDescriptor

var file_tests_integration_plugins_config_proto_rawDesc = []byte{
	0x0a, 0x26, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x6d, 0x6f, 0x65, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x22, 0x7a, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x04, 0x6e, 0x65, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x42, 0x27, 0x5a, 0x25, 0x6d, 0x6f, 0x73, 0x6e, 0x2e, 0x69, 0x6f, 0x2f, 0x6d,
	0x6f, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_integration_plugins_config_proto_rawDescOnce sync.Once
	file_tests_integration_plugins_config_proto_rawDescData = file_tests_integration_plugins_config_proto_rawDesc
)

func file_tests_integration_plugins_config_proto_rawDescGZIP() []byte {
	file_tests_integration_plugins_config_proto_rawDescOnce.Do(func() {
		file_tests_integration_plugins_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_integration_plugins_config_proto_rawDescData)
	})
	return file_tests_integration_plugins_config_proto_rawDescData
}

var file_tests_integration_plugins_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_integration_plugins_config_proto_goTypes = []interface{}{
	(*Config)(nil), // 0: moe.tests.integration.plugins.Config
}
var file_tests_integration_plugins_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_integration_plugins_config_proto_init() }
func file_tests_integration_plugins_config_proto_init() {
	if File_tests_integration_plugins_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_integration_plugins_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_integration_plugins_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_integration_plugins_config_proto_goTypes,
		DependencyIndexes: file_tests_integration_plugins_config_proto_depIdxs,
		MessageInfos:      file_tests_integration_plugins_config_proto_msgTypes,
	}.Build()
	File_tests_integration_plugins_config_proto = out.File
	file_tests_integration_plugins_config_proto_rawDesc = nil
	file_tests_integration_plugins_config_proto_goTypes = nil
	file_tests_integration_plugins_config_proto_depIdxs = nil
}
