apiVersion: v1
kind: Service
metadata:
  name: nacos-service
  namespace: e2e
spec:
  selector:
    app: nacos
  ports:
  - name: nacos
    port: 8848
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: e2e
  name: nacos
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v1.4.6-slim
        ports:
        - containerPort: 8848
        env:
        - name: PREFER_HOST_MODE
          value: hostname
        - name: MODE
          value: standalone
        - name: JVM_XMS
          value: 512m
        - name: JVM_XMX
          value: 512m
