/*
Copyright The HTNN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"

	v1 "mosn.io/htnn/types/apis/v1"
	scheme "mosn.io/htnn/types/pkg/client/clientset/versioned/scheme"
)

// ServiceRegistriesGetter has a method to return a ServiceRegistryInterface.
// A group's client should implement this interface.
type ServiceRegistriesGetter interface {
	ServiceRegistries(namespace string) ServiceRegistryInterface
}

// ServiceRegistryInterface has methods to work with ServiceRegistry resources.
type ServiceRegistryInterface interface {
	Create(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.CreateOptions) (*v1.ServiceRegistry, error)
	Update(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.UpdateOptions) (*v1.ServiceRegistry, error)
	UpdateStatus(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.UpdateOptions) (*v1.ServiceRegistry, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ServiceRegistry, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ServiceRegistryList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceRegistry, err error)
	ServiceRegistryExpansion
}

// serviceRegistries implements ServiceRegistryInterface
type serviceRegistries struct {
	client rest.Interface
	ns     string
}

// newServiceRegistries returns a ServiceRegistries
func newServiceRegistries(c *ApisV1Client, namespace string) *serviceRegistries {
	return &serviceRegistries{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceRegistry, and returns the corresponding serviceRegistry object, and an error if there is any.
func (c *serviceRegistries) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ServiceRegistry, err error) {
	result = &v1.ServiceRegistry{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceregistries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceRegistries that match those selectors.
func (c *serviceRegistries) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ServiceRegistryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ServiceRegistryList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceRegistries.
func (c *serviceRegistries) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("serviceregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a serviceRegistry and creates it.  Returns the server's representation of the serviceRegistry, and an error, if there is any.
func (c *serviceRegistries) Create(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.CreateOptions) (result *v1.ServiceRegistry, err error) {
	result = &v1.ServiceRegistry{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("serviceregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceRegistry).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a serviceRegistry and updates it. Returns the server's representation of the serviceRegistry, and an error, if there is any.
func (c *serviceRegistries) Update(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.UpdateOptions) (result *v1.ServiceRegistry, err error) {
	result = &v1.ServiceRegistry{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceregistries").
		Name(serviceRegistry.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceRegistry).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *serviceRegistries) UpdateStatus(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.UpdateOptions) (result *v1.ServiceRegistry, err error) {
	result = &v1.ServiceRegistry{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceregistries").
		Name(serviceRegistry.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceRegistry).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the serviceRegistry and deletes it. Returns an error if one occurs.
func (c *serviceRegistries) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceregistries").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceRegistries) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceregistries").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched serviceRegistry.
func (c *serviceRegistries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceRegistry, err error) {
	result = &v1.ServiceRegistry{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("serviceregistries").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
