---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-htnn.mosn.io-v1-consumer
  failurePolicy: Fail
  name: mconsumer.kb.io
  rules:
  - apiGroups:
    - mosn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - consumers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-htnn.mosn.io-v1-httpfilterpolicy
  failurePolicy: Fail
  name: mhttpfilterpolicy.kb.io
  rules:
  - apiGroups:
    - mosn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - httpfilterpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-htnn.mosn.io-v1-serviceregistry
  failurePolicy: Fail
  name: mserviceregistry.kb.io
  rules:
  - apiGroups:
    - mosn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceregistries
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-istio-io-v1beta1-virtualservice
  failurePolicy: Fail
  name: mvirtualservice.kb.io
  rules:
  - apiGroups:
    - networking.istio.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualservices
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-htnn.mosn.io-v1-consumer
  failurePolicy: Fail
  name: vconsumer.kb.io
  rules:
  - apiGroups:
    - mosn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - consumers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-htnn.mosn.io-v1-httpfilterpolicy
  failurePolicy: Fail
  name: vhttpfilterpolicy.kb.io
  rules:
  - apiGroups:
    - mosn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - httpfilterpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-htnn.mosn.io-v1-serviceregistry
  failurePolicy: Fail
  name: vserviceregistry.kb.io
  rules:
  - apiGroups:
    - mosn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - serviceregistries
  sideEffects: None
