// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0--rc1
// source: types/plugins/acl/config.proto

package acl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义 ACL 插件的配置
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 允许的 IP 地址列表
	AllowList []string `protobuf:"bytes,1,rep,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	// 拒绝的 IP 地址列表
	DenyList      []string `protobuf:"bytes,2,rep,name=deny_list,json=denyList,proto3" json:"deny_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_types_plugins_acl_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_types_plugins_acl_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_types_plugins_acl_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetAllowList() []string {
	if x != nil {
		return x.AllowList
	}
	return nil
}

func (x *Config) GetDenyList() []string {
	if x != nil {
		return x.DenyList
	}
	return nil
}

var File_types_plugins_acl_config_proto protoreflect.FileDescriptor

const file_types_plugins_acl_config_proto_rawDesc = "" +
	"\n" +
	"\x1etypes/plugins/acl/config.proto\x12\x11types.plugins.acl\"D\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"allow_list\x18\x01 \x03(\tR\tallowList\x12\x1b\n" +
	"\tdeny_list\x18\x02 \x03(\tR\bdenyListB Z\x1emosn.io/htnn/types/plugins/aclb\x06proto3"

var (
	file_types_plugins_acl_config_proto_rawDescOnce sync.Once
	file_types_plugins_acl_config_proto_rawDescData []byte
)

func file_types_plugins_acl_config_proto_rawDescGZIP() []byte {
	file_types_plugins_acl_config_proto_rawDescOnce.Do(func() {
		file_types_plugins_acl_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_plugins_acl_config_proto_rawDesc), len(file_types_plugins_acl_config_proto_rawDesc)))
	})
	return file_types_plugins_acl_config_proto_rawDescData
}

var file_types_plugins_acl_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_plugins_acl_config_proto_goTypes = []any{
	(*Config)(nil), // 0: types.plugins.acl.Config
}
var file_types_plugins_acl_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_plugins_acl_config_proto_init() }
func file_types_plugins_acl_config_proto_init() {
	if File_types_plugins_acl_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_plugins_acl_config_proto_rawDesc), len(file_types_plugins_acl_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_plugins_acl_config_proto_goTypes,
		DependencyIndexes: file_types_plugins_acl_config_proto_depIdxs,
		MessageInfos:      file_types_plugins_acl_config_proto_msgTypes,
	}.Build()
	File_types_plugins_acl_config_proto = out.File
	file_types_plugins_acl_config_proto_goTypes = nil
	file_types_plugins_acl_config_proto_depIdxs = nil
}
