# Copyright The HTNN Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM --platform=$TARGETPLATFORM golang:1.21-bullseye

# If this image is changed, tell @spacewander to push it.
# TODO: Maybe we can push this image automatically by tag?

# This Docker image provides the command line tools which can't be managed by `go`

# Labels below are consumed by GitHub Container Registry
# See https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images
LABEL org.opencontainers.image.source=https://github.com/mosn/htnn
LABEL org.opencontainers.image.description="This image contains tools for the HTNN project."
LABEL org.opencontainers.image.licenses="Apache-2.0"

#For Chinese developers
RUN sed -i 's#http://deb.debian.org#https://mirrors.163.com#g' /etc/apt/sources.list
ARG GOPROXY
ENV GOPROXY=$GOPROXY

# codespell
# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y --no-install-recommends pip && pip install --no-cache-dir codespell==2.2.6

# protoc
# hadolint ignore=DL3008
RUN apt-get install -y --no-install-recommends unzip
# I have researched https://github.com/bufbuild/protovalidate/ which claims itself as the successor of protoc-gen-validate.
# Currently (2023 year), this project looks experimental and it has lots of break change compared with protoc-gen-validate.
# So we still stick on the protoc-gen-validate.
RUN VER=1.0.2 && \
    set -ex && \
    git clone https://github.com/bufbuild/protoc-gen-validate -b v${VER} --depth 1 /go/src/protoc-gen-validate
# Break down the git clone & wget so that we can cache git repo early
RUN VER=1.0.2 && \
    ARCH=$(dpkg --print-architecture) && \
    set -ex && \
    wget https://github.com/bufbuild/protoc-gen-validate/releases/download/v${VER}/protoc-gen-validate_${VER}_linux_${ARCH}.tar.gz && \
    tar -zxvpf protoc-gen-validate_${VER}_linux_${ARCH}.tar.gz && \
    mv protoc-gen-validate-go /usr/bin && \
    mv protoc-gen-validate /usr/bin
RUN VER=24.4 && \
    ARCH=$(dpkg --print-architecture) && \
    set -ex && \
    case "${ARCH}" in \
      amd64) \
        NAME=protoc-${VER}-linux-x86_64.zip \
        ;; \
      arm64) \
        NAME=protoc-${VER}-linux-aarch_64.zip \
        ;; \
    esac && \
    wget https://github.com/protocolbuffers/protobuf/releases/download/v${VER}/${NAME} && \
    unzip -o ${NAME} -d /usr/local bin/protoc && \
    unzip -o ${NAME} -d /usr/local 'include/*' && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0

# clang-format
RUN pip install --no-cache-dir clang-format==17.0.6
