/*
Copyright The HTNN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1 "mosn.io/htnn/types/apis/v1"
)

// FakeHTTPFilterPolicies implements HTTPFilterPolicyInterface
type FakeHTTPFilterPolicies struct {
	Fake *FakeApisV1
	ns   string
}

var httpfilterpoliciesResource = v1.SchemeGroupVersion.WithResource("httpfilterpolicies")

var httpfilterpoliciesKind = v1.SchemeGroupVersion.WithKind("HTTPFilterPolicy")

// Get takes name of the hTTPFilterPolicy, and returns the corresponding hTTPFilterPolicy object, and an error if there is any.
func (c *FakeHTTPFilterPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.HTTPFilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(httpfilterpoliciesResource, c.ns, name), &v1.HTTPFilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HTTPFilterPolicy), err
}

// List takes label and field selectors, and returns the list of HTTPFilterPolicies that match those selectors.
func (c *FakeHTTPFilterPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.HTTPFilterPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(httpfilterpoliciesResource, httpfilterpoliciesKind, c.ns, opts), &v1.HTTPFilterPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.HTTPFilterPolicyList{ListMeta: obj.(*v1.HTTPFilterPolicyList).ListMeta}
	for _, item := range obj.(*v1.HTTPFilterPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hTTPFilterPolicies.
func (c *FakeHTTPFilterPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(httpfilterpoliciesResource, c.ns, opts))

}

// Create takes the representation of a hTTPFilterPolicy and creates it.  Returns the server's representation of the hTTPFilterPolicy, and an error, if there is any.
func (c *FakeHTTPFilterPolicies) Create(ctx context.Context, hTTPFilterPolicy *v1.HTTPFilterPolicy, opts metav1.CreateOptions) (result *v1.HTTPFilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(httpfilterpoliciesResource, c.ns, hTTPFilterPolicy), &v1.HTTPFilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HTTPFilterPolicy), err
}

// Update takes the representation of a hTTPFilterPolicy and updates it. Returns the server's representation of the hTTPFilterPolicy, and an error, if there is any.
func (c *FakeHTTPFilterPolicies) Update(ctx context.Context, hTTPFilterPolicy *v1.HTTPFilterPolicy, opts metav1.UpdateOptions) (result *v1.HTTPFilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(httpfilterpoliciesResource, c.ns, hTTPFilterPolicy), &v1.HTTPFilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HTTPFilterPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHTTPFilterPolicies) UpdateStatus(ctx context.Context, hTTPFilterPolicy *v1.HTTPFilterPolicy, opts metav1.UpdateOptions) (*v1.HTTPFilterPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(httpfilterpoliciesResource, "status", c.ns, hTTPFilterPolicy), &v1.HTTPFilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HTTPFilterPolicy), err
}

// Delete takes name of the hTTPFilterPolicy and deletes it. Returns an error if one occurs.
func (c *FakeHTTPFilterPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(httpfilterpoliciesResource, c.ns, name, opts), &v1.HTTPFilterPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHTTPFilterPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(httpfilterpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.HTTPFilterPolicyList{})
	return err
}

// Patch applies the patch and returns the patched hTTPFilterPolicy.
func (c *FakeHTTPFilterPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.HTTPFilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(httpfilterpoliciesResource, c.ns, name, pt, data, subresources...), &v1.HTTPFilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.HTTPFilterPolicy), err
}
