/*
Copyright The HTNN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1 "mosn.io/htnn/types/apis/v1"
)

// FakeServiceRegistries implements ServiceRegistryInterface
type FakeServiceRegistries struct {
	Fake *FakeApisV1
	ns   string
}

var serviceregistriesResource = v1.SchemeGroupVersion.WithResource("serviceregistries")

var serviceregistriesKind = v1.SchemeGroupVersion.WithKind("ServiceRegistry")

// Get takes name of the serviceRegistry, and returns the corresponding serviceRegistry object, and an error if there is any.
func (c *FakeServiceRegistries) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ServiceRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(serviceregistriesResource, c.ns, name), &v1.ServiceRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceRegistry), err
}

// List takes label and field selectors, and returns the list of ServiceRegistries that match those selectors.
func (c *FakeServiceRegistries) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ServiceRegistryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(serviceregistriesResource, serviceregistriesKind, c.ns, opts), &v1.ServiceRegistryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ServiceRegistryList{ListMeta: obj.(*v1.ServiceRegistryList).ListMeta}
	for _, item := range obj.(*v1.ServiceRegistryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested serviceRegistries.
func (c *FakeServiceRegistries) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(serviceregistriesResource, c.ns, opts))

}

// Create takes the representation of a serviceRegistry and creates it.  Returns the server's representation of the serviceRegistry, and an error, if there is any.
func (c *FakeServiceRegistries) Create(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.CreateOptions) (result *v1.ServiceRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(serviceregistriesResource, c.ns, serviceRegistry), &v1.ServiceRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceRegistry), err
}

// Update takes the representation of a serviceRegistry and updates it. Returns the server's representation of the serviceRegistry, and an error, if there is any.
func (c *FakeServiceRegistries) Update(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.UpdateOptions) (result *v1.ServiceRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(serviceregistriesResource, c.ns, serviceRegistry), &v1.ServiceRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceRegistry), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServiceRegistries) UpdateStatus(ctx context.Context, serviceRegistry *v1.ServiceRegistry, opts metav1.UpdateOptions) (*v1.ServiceRegistry, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(serviceregistriesResource, "status", c.ns, serviceRegistry), &v1.ServiceRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceRegistry), err
}

// Delete takes name of the serviceRegistry and deletes it. Returns an error if one occurs.
func (c *FakeServiceRegistries) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(serviceregistriesResource, c.ns, name, opts), &v1.ServiceRegistry{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeServiceRegistries) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(serviceregistriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ServiceRegistryList{})
	return err
}

// Patch applies the patch and returns the patched serviceRegistry.
func (c *FakeServiceRegistries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ServiceRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(serviceregistriesResource, c.ns, name, pt, data, subresources...), &v1.ServiceRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ServiceRegistry), err
}
