/*
Copyright The HTNN Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1 "mosn.io/htnn/types/apis/v1"
)

// FakeFilterPolicies implements FilterPolicyInterface
type FakeFilterPolicies struct {
	Fake *FakeApisV1
	ns   string
}

var filterpoliciesResource = v1.SchemeGroupVersion.WithResource("filterpolicies")

var filterpoliciesKind = v1.SchemeGroupVersion.WithKind("FilterPolicy")

// Get takes name of the filterPolicy, and returns the corresponding filterPolicy object, and an error if there is any.
func (c *FakeFilterPolicies) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.FilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(filterpoliciesResource, c.ns, name), &v1.FilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.FilterPolicy), err
}

// List takes label and field selectors, and returns the list of FilterPolicies that match those selectors.
func (c *FakeFilterPolicies) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FilterPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(filterpoliciesResource, filterpoliciesKind, c.ns, opts), &v1.FilterPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.FilterPolicyList{ListMeta: obj.(*v1.FilterPolicyList).ListMeta}
	for _, item := range obj.(*v1.FilterPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested filterPolicies.
func (c *FakeFilterPolicies) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(filterpoliciesResource, c.ns, opts))

}

// Create takes the representation of a filterPolicy and creates it.  Returns the server's representation of the filterPolicy, and an error, if there is any.
func (c *FakeFilterPolicies) Create(ctx context.Context, filterPolicy *v1.FilterPolicy, opts metav1.CreateOptions) (result *v1.FilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(filterpoliciesResource, c.ns, filterPolicy), &v1.FilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.FilterPolicy), err
}

// Update takes the representation of a filterPolicy and updates it. Returns the server's representation of the filterPolicy, and an error, if there is any.
func (c *FakeFilterPolicies) Update(ctx context.Context, filterPolicy *v1.FilterPolicy, opts metav1.UpdateOptions) (result *v1.FilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(filterpoliciesResource, c.ns, filterPolicy), &v1.FilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.FilterPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFilterPolicies) UpdateStatus(ctx context.Context, filterPolicy *v1.FilterPolicy, opts metav1.UpdateOptions) (*v1.FilterPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(filterpoliciesResource, "status", c.ns, filterPolicy), &v1.FilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.FilterPolicy), err
}

// Delete takes name of the filterPolicy and deletes it. Returns an error if one occurs.
func (c *FakeFilterPolicies) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(filterpoliciesResource, c.ns, name, opts), &v1.FilterPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFilterPolicies) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(filterpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.FilterPolicyList{})
	return err
}

// Patch applies the patch and returns the patched filterPolicy.
func (c *FakeFilterPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.FilterPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(filterpoliciesResource, c.ns, name, pt, data, subresources...), &v1.FilterPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.FilterPolicy), err
}
